user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
    multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /tmp/nginx-access.log;
    error_log  /tmp/nginx-error.log warn;

    server {
        listen 8080 default_server;

        location / {
            fastcgi_pass 127.0.0.1:9993;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/qgis_mapserv.fcgi;
            fastcgi_read_timeout  300;
            fastcgi_send_timeout  300;
            fastcgi_buffer_size   32k;
            fastcgi_buffers       8 32k;
            client_max_body_size  10M;
        }
    }
}
